flowchart TD
    %% 事件链依赖关系图

    subgraph Chain0[链 0: 1个事件]
        event_exam_747[event_ex]
    end

    subgraph Chain1[链 1: 1个事件]
        event_intro_745[event_in]
    end

    subgraph Chain2[链 2: 1个事件]
        duotai_humiliation_a[duotai_h]
    end

    subgraph Chain3[链 3: 1个事件]
        duotai_humiliation_a[duotai_h]
    end

    subgraph Chain4[链 4: 1个事件]
        duotai_humiliation_a[duotai_h]
    end

    subgraph Chain5[链 5: 1个事件]
        duotai_humiliation_a[duotai_h]
    end

    subgraph Chain6[链 6: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain7[链 7: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain8[链 8: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain9[链 9: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain10[链 10: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain11[链 11: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain12[链 12: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain13[链 13: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain14[链 14: 1个事件]
        duotai_humiliation_p[duotai_h]
    end

    subgraph Chain15[链 15: 1个事件]
        duotai_humiliation_p[duotai_h]
    end

    subgraph Chain16[链 16: 1个事件]
        duotai_humiliation_p[duotai_h]
    end

    subgraph Chain17[链 17: 1个事件]
        duotai_humiliation_p[duotai_h]
    end

    subgraph Chain18[链 18: 1个事件]
        qingliu_passive_bene[qingliu_]
    end

    subgraph Chain19[链 19: 1个事件]
        zhuoliu_lieqi_ghostw[zhuoliu_]
    end

    subgraph Chain20[链 20: 1个事件]
        kuangke_zhuoliu_zoo_[kuangke_]
    end

    subgraph Chain21[链 21: 1个事件]
        zhuoliu_zuanying_gho[zhuoliu_]
    end

    subgraph Chain22[链 22: 1个事件]
        qingliu_fengying_aes[qingliu_]
    end

    subgraph Chain23[链 23: 1个事件]
        zhuoliu_fengying_bor[zhuoliu_]
    end

    subgraph Chain24[链 24: 1个事件]
        kuangke_zhuoliu_mali[kuangke_]
    end

    subgraph Chain25[链 25: 1个事件]
        qingliu_daoxin_posui[qingliu_]
    end

    subgraph Chain26[链 26: 1个事件]
        zhuoliu_fengying_rel[zhuoliu_]
    end

    subgraph Chain27[链 27: 1个事件]
        qingliu_daoxin_posui[qingliu_]
    end

    subgraph Chain28[链 28: 1个事件]
        qingliu_fengying_mud[qingliu_]
    end

    subgraph Chain29[链 29: 1个事件]
        bai_ye_honeymoon_l0_[bai_ye_h]
    end

    subgraph Chain30[链 30: 1个事件]
        bai_ye_honeymoon_l0_[bai_ye_h]
    end

    subgraph Chain31[链 31: 1个事件]
        bai_ye_honeymoon_l2_[bai_ye_h]
    end

    subgraph Chain32[链 32: 1个事件]
        bai_ye_honeymoon_l1_[bai_ye_h]
    end

    subgraph Chain33[链 33: 1个事件]
        bai_ye_honeymoon_l2_[bai_ye_h]
    end

    subgraph Chain34[链 34: 1个事件]
        bai_ye_honeymoon_l1_[bai_ye_h]
    end

    subgraph Chain35[链 35: 1个事件]
        bai_ye_honeymoon_l0_[bai_ye_h]
    end

    subgraph Chain36[链 36: 1个事件]
        bai_ye_honeymoon_l0_[bai_ye_h]
    end

    subgraph Chain37[链 37: 1个事件]
        bai_ye_honeymoon_l2_[bai_ye_h]
    end

    subgraph Chain38[链 38: 1个事件]
        bai_ye_honeymoon_l0_[bai_ye_h]
    end

    subgraph Chain39[链 39: 1个事件]
        bai_ye_honeymoon_l0_[bai_ye_h]
    end

    subgraph Chain40[链 40: 1个事件]
        bai_ye_honeymoon_l1_[bai_ye_h]
    end

    subgraph Chain41[链 41: 1个事件]
        bai_ye_honeymoon_l2_[bai_ye_h]
    end

    subgraph Chain42[链 42: 1个事件]
        bai_ye_honeymoon_l1_[bai_ye_h]
    end

    subgraph Chain43[链 43: 1个事件]
        bai_ye_honeymoon_l0_[bai_ye_h]
    end

    subgraph Chain44[链 44: 1个事件]
        bai_ye_honeymoon_l1_[bai_ye_h]
    end

    subgraph Chain45[链 45: 1个事件]
        bai_ye_honeymoon_l2_[bai_ye_h]
    end

    subgraph Chain46[链 46: 1个事件]
        bai_ye_honeymoon_l0_[bai_ye_h]
    end

    subgraph Chain47[链 47: 1个事件]
        bai_ye_honeymoon_l1_[bai_ye_h]
    end

    subgraph Chain48[链 48: 1个事件]
        bai_ye_honeymoon_l2_[bai_ye_h]
    end

    subgraph Chain49[链 49: 1个事件]
        bai_ye_honeymoon_l2_[bai_ye_h]
    end

    subgraph Chain50[链 50: 1个事件]
        bai_ye_honeymoon_l1_[bai_ye_h]
    end

    subgraph Chain51[链 51: 1个事件]
        bai_ye_honeymoon_l1_[bai_ye_h]
    end

    subgraph Chain52[链 52: 1个事件]
        bai_ye_honeymoon_l2_[bai_ye_h]
    end

    subgraph Chain53[链 53: 1个事件]
        bai_ye_honeymoon_l2_[bai_ye_h]
    end

    subgraph Chain54[链 54: 1个事件]
        bai_ye_honeymoon_l1_[bai_ye_h]
    end

    subgraph Chain55[链 55: 1个事件]
        bai_ye_honeymoon_l0_[bai_ye_h]
    end

    subgraph Chain56[链 56: 1个事件]
        bai_ye_real_appearan[bai_ye_r]
    end

    subgraph Chain57[链 57: 1个事件]
        bai_ye_real_appearan[bai_ye_r]
    end

    subgraph Chain58[链 58: 1个事件]
        bai_ye_real_appearan[bai_ye_r]
    end

    subgraph Chain59[链 59: 1个事件]
        bai_ye_real_appearan[bai_ye_r]
    end

    subgraph Chain60[链 60: 1个事件]
        bai_ye_real_appearan[bai_ye_r]
    end

    subgraph Chain61[链 61: 1个事件]
        bai_ye_real_appearan[bai_ye_r]
    end

    subgraph Chain62[链 62: 1个事件]
        bai_ye_real_appearan[bai_ye_r]
    end

    subgraph Chain63[链 63: 1个事件]
        bai_ye_real_appearan[bai_ye_r]
    end

    subgraph Chain64[链 64: 1个事件]
        bai_ye_real_appearan[bai_ye_r]
    end

    subgraph Chain65[链 65: 1个事件]
        normal_ji_lv[normal_j]
    end

    subgraph Chain66[链 66: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain67[链 67: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain68[链 68: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain69[链 69: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain70[链 70: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain71[链 71: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain72[链 72: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain73[链 73: 1个事件]
        duotai_humiliation_c[duotai_h]
    end

    subgraph Chain74[链 74: 1个事件]
        duotai_humiliation_h[duotai_h]
    end

    subgraph Chain75[链 75: 1个事件]
        duotai_humiliation_h[duotai_h]
    end

    subgraph Chain76[链 76: 1个事件]
        duotai_humiliation_h[duotai_h]
    end

    subgraph Chain77[链 77: 1个事件]
        duotai_humiliation_h[duotai_h]
    end

    subgraph Chain78[链 78: 1个事件]
        duotai_humiliation_h[duotai_h]
    end

    subgraph Chain79[链 79: 1个事件]
        duotai_humiliation_h[duotai_h]
    end

    subgraph Chain80[链 80: 1个事件]
        duotai_humiliation_l[duotai_h]
    end

    subgraph Chain81[链 81: 1个事件]
        duotai_humiliation_l[duotai_h]
    end

    subgraph Chain82[链 82: 1个事件]
        duotai_humiliation_l[duotai_h]
    end

    subgraph Chain83[链 83: 1个事件]
        duotai_humiliation_l[duotai_h]
    end

    subgraph Chain84[链 84: 1个事件]
        duotai_humiliation_t[duotai_h]
    end

    subgraph Chain85[链 85: 1个事件]
        duotai_humiliation_t[duotai_h]
    end

    subgraph Chain86[链 86: 1个事件]
        duotai_humiliation_t[duotai_h]
    end

    subgraph Chain87[链 87: 1个事件]
        duotai_humiliation_t[duotai_h]
    end

    subgraph Chain88[链 88: 1个事件]
        duotai_humiliation_t[duotai_h]
    end

    subgraph Chain89[链 89: 1个事件]
        duotai_humiliation_t[duotai_h]
    end

    subgraph Chain90[链 90: 1个事件]
        duotai_humiliation_t[duotai_h]
    end

    subgraph Chain91[链 91: 1个事件]
        duotai_humiliation_t[duotai_h]
    end

    subgraph Chain92[链 92: 1个事件]
        zize_pawn_jade[zize_paw]
    end

    subgraph Chain93[链 93: 1个事件]
        qingliu_fengying_tem[qingliu_]
    end

    subgraph Chain94[链 94: 1个事件]
        qingliu_daoxin_posui[qingliu_]
    end

    subgraph Chain95[链 95: 1个事件]
        zhuoliu_zuanying_pov[zhuoliu_]
    end

    subgraph Chain96[链 96: 1个事件]
        qingliu_passive_bene[qingliu_]
    end

    subgraph Chain97[链 97: 1个事件]
        kuangke_zhuoliu_toxi[kuangke_]
    end

    subgraph Chain98[链 98: 1个事件]
        qingliu_passive_bene[qingliu_]
    end

    subgraph Chain99[链 99: 1个事件]
        qingliu_fengying_paw[qingliu_]
    end

    subgraph Chain100[链 100: 1个事件]
        qingliu_daoxin_posui[qingliu_]
    end

    subgraph Chain101[链 101: 1个事件]
        qingliu_zuanying_ski[qingliu_]
    end

    subgraph Chain102[链 102: 1个事件]
        qingliu_jiaolv_illus[qingliu_]
    end

    subgraph Chain103[链 103: 1个事件]
        zhuoliu_lieqi_povert[zhuoliu_]
    end

    subgraph Chain104[链 104: 1个事件]
        qingliu_zuanying_paw[qingliu_]
    end

    subgraph Chain105[链 105: 1个事件]
        zhuoliu_fengying_dis[zhuoliu_]
    end

    subgraph Chain106[链 106: 1个事件]
        zize_young_scholar[zize_you]
    end

    subgraph Chain107[链 107: 1个事件]
        qingliu_passive_bene[qingliu_]
    end

    subgraph Chain108[链 108: 1个事件]
        qingliu_jiaolv_statu[qingliu_]
    end

    subgraph Chain109[链 109: 1个事件]
        qingliu_passive_bene[qingliu_]
    end

    subgraph Chain110[链 110: 1个事件]
        zize_frozen_corpse[zize_fro]
    end

    subgraph Chain111[链 111: 1个事件]
        kuangke_qingliu_gaos[kuangke_]
    end

    subgraph Chain112[链 112: 1个事件]
        kuangke_zhuoliu_pers[kuangke_]
    end

    subgraph Chain113[链 113: 1个事件]
        zhuoliu_zuanying_end[zhuoliu_]
    end

    subgraph Chain114[链 114: 1个事件]
        zhuoliu_fengying_led[zhuoliu_]
    end

    subgraph Chain115[链 115: 1个事件]
        kuangke_qingliu_zhen[kuangke_]
    end

    subgraph Chain116[链 116: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain117[链 117: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain118[链 118: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain119[链 119: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain120[链 120: 1个事件]
        normal_shan_shui[normal_s]
    end

    subgraph Chain121[链 121: 1个事件]
        normal_ying_zhi[normal_y]
    end

    subgraph Chain122[链 122: 1个事件]
        duotai_humiliation_w[duotai_h]
    end

    subgraph Chain123[链 123: 1个事件]
        duotai_humiliation_w[duotai_h]
    end

    subgraph Chain124[链 124: 1个事件]
        duotai_humiliation_w[duotai_h]
    end

    subgraph Chain125[链 125: 1个事件]
        duotai_humiliation_w[duotai_h]
    end

    subgraph Chain126[链 126: 1个事件]
        747kuangda_denggao_s[747kuang]
    end

    subgraph Chain127[链 127: 1个事件]
        747kuangda_denggao_s[747kuang]
    end

    subgraph Chain128[链 128: 1个事件]
        747kuangda_denggao_s[747kuang]
    end

    subgraph Chain129[链 129: 1个事件]
        747kuangda_denggao_s[747kuang]
    end

    subgraph Chain130[链 130: 1个事件]
        747kuangda_denggao_s[747kuang]
    end

    subgraph Chain131[链 131: 1个事件]
        kuangke_qingliu_gaos[kuangke_]
    end

    subgraph Chain132[链 132: 1个事件]
        kuangke_qingliu_zhen[kuangke_]
    end

    subgraph Chain133[链 133: 1个事件]
        kuangke_qingliu_wang[kuangke_]
    end

    subgraph Chain134[链 134: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain135[链 135: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain136[链 136: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain137[链 137: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain138[链 138: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain139[链 139: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain140[链 140: 1个事件]
        747kuangda_denggao_l[747kuang]
    end

    subgraph Chain141[链 141: 1个事件]
        747kuangda_denggao_l[747kuang]
    end

    subgraph Chain142[链 142: 1个事件]
        747kuangda_denggao_l[747kuang]
    end

    subgraph Chain143[链 143: 1个事件]
        747kuangda_denggao_l[747kuang]
    end

    subgraph Chain144[链 144: 1个事件]
        747kuangda_denggao_l[747kuang]
    end

    subgraph Chain145[链 145: 1个事件]
        747kuangda_denggao_l[747kuang]
    end

    subgraph Chain146[链 146: 1个事件]
        747kuangda_denggao_l[747kuang]
    end

    subgraph Chain147[链 147: 1个事件]
        747kuangda_denggao_l[747kuang]
    end

    subgraph Chain148[链 148: 1个事件]
        747kuangda_denggao_p[747kuang]
    end

    subgraph Chain149[链 149: 1个事件]
        747kuangda_denggao_p[747kuang]
    end

    subgraph Chain150[链 150: 1个事件]
        747kuangda_denggao_p[747kuang]
    end

    subgraph Chain151[链 151: 1个事件]
        747kuangda_denggao_p[747kuang]
    end

    subgraph Chain152[链 152: 1个事件]
        747kuangda_denggao_p[747kuang]
    end

    subgraph Chain153[链 153: 1个事件]
        zize_wine_boy_identi[zize_win]
    end

    subgraph Chain154[链 154: 1个事件]
        qingliu_daoxin_posui[qingliu_]
    end

    subgraph Chain155[链 155: 1个事件]
        kuangke_zhuoliu_blee[kuangke_]
    end

    subgraph Chain156[链 156: 1个事件]
        qingliu_jiaolv_dooms[qingliu_]
    end

    subgraph Chain157[链 157: 1个事件]
        zize_wine_boy[zize_win]
    end

    subgraph Chain158[链 158: 1个事件]
        qingliu_daoxin_posui[qingliu_]
    end

    subgraph Chain159[链 159: 1个事件]
        qingliu_daoxin_posui[qingliu_]
    end

    subgraph Chain160[链 160: 1个事件]
        zize_home_letter[zize_hom]
    end

    subgraph Chain161[链 161: 1个事件]
        zhuoliu_lieqi_hijack[zhuoliu_]
    end

    subgraph Chain162[链 162: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain163[链 163: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain164[链 164: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain165[链 165: 1个事件]
        kuangke_zhuoliu_prid[kuangke_]
    end

    subgraph Chain166[链 166: 1个事件]
        zhuoliu_zuanying_int[zhuoliu_]
    end

    subgraph Chain167[链 167: 1个事件]
        zhuoliu_zuanying_gat[zhuoliu_]
    end

    subgraph Chain168[链 168: 1个事件]
        zhuoliu_lieqi_swill_[zhuoliu_]
    end

    subgraph Chain169[链 169: 1个事件]
        qingliu_passive_bene[qingliu_]
    end

    subgraph Chain170[链 170: 1个事件]
        qingliu_zuanying_gho[qingliu_]
    end

    subgraph Chain171[链 171: 1个事件]
        qingliu_jiaolv_fomo_[qingliu_]
    end

    subgraph Chain172[链 172: 1个事件]
        qingliu_passive_bene[qingliu_]
    end

    subgraph Chain173[链 173: 1个事件]
        zize_old_friend[zize_old]
    end

    subgraph Chain174[链 174: 1个事件]
        qingliu_fengying_gho[qingliu_]
    end

    subgraph Chain175[链 175: 1个事件]
        zhuoliu_fengying_ban[zhuoliu_]
    end

    subgraph Chain176[链 176: 1个事件]
        qingliu_zuanying_dou[qingliu_]
    end

    subgraph Chain177[链 177: 1个事件]
        kuangke_qingliu_wang[kuangke_]
    end

    subgraph Chain178[链 178: 1个事件]
        qingliu_daoxin_posui[qingliu_]
    end

    subgraph Chain179[链 179: 1个事件]
        qingliu_fengying_pin[qingliu_]
    end

    subgraph Chain180[链 180: 1个事件]
        qingliu_zuanying_gho[qingliu_]
    end

    subgraph Chain181[链 181: 1个事件]
        qingliu_passive_bene[qingliu_]
    end

    subgraph Chain182[链 182: 1个事件]
        kuangke_qingliu_liba[kuangke_]
    end

    subgraph Chain183[链 183: 1个事件]
        zhuoliu_lieqi_cockfi[zhuoliu_]
    end

    subgraph Chain184[链 184: 1个事件]
        qingliu_zuanying_mon[qingliu_]
    end

    subgraph Chain185[链 185: 1个事件]
        zhuoliu_fengying_sil[zhuoliu_]
    end

    subgraph Chain186[链 186: 1个事件]
        qingliu_zuanying_dou[qingliu_]
    end

    subgraph Chain187[链 187: 1个事件]
        qingliu_daoxin_posui[qingliu_]
    end

    subgraph Chain188[链 188: 1个事件]
        kuangke_qingliu_liba[kuangke_]
    end

    subgraph Chain189[链 189: 1个事件]
        zhuoliu_zuanying_din[zhuoliu_]
    end

    subgraph Chain190[链 190: 1个事件]
        qingliu_zuanying_tri[qingliu_]
    end

    subgraph Chain191[链 191: 1个事件]
        qingliu_daoxin_posui[qingliu_]
    end

    subgraph Chain192[链 192: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain193[链 193: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain194[链 194: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain195[链 195: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain196[链 196: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain197[链 197: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain198[链 198: 1个事件]
        normal_gan_ye[normal_g]
    end

    subgraph Chain199[链 199: 1个事件]
        normal_zeng_da[normal_z]
    end

    subgraph Chain200[链 200: 1个事件]
        normal_jiao_you[normal_j]
    end

    subgraph Chain201[链 201: 1个事件]
        event_death_health_l[event_de]
    end

    subgraph Chain202[链 202: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain203[链 203: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain204[链 204: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain205[链 205: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain206[链 206: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain207[链 207: 1个事件]
        scene_imagery_librar[scene_im]
    end

    subgraph Chain208[链 208: 1个事件]
        normal_bai_ye[normal_b]
    end

    subgraph Chain209[链 209: 1个事件]
        normal_feng_zhao[normal_f]
    end

    subgraph Chain210[链 210: 1个事件]
        normal_fang_shi[normal_f]
    end

    subgraph Chain211[链 211: 1个事件]
        normal_huai_gu[normal_h]
    end

    subgraph Chain212[链 212: 1个事件]
        sensual_huxuan_dance[sensual_]
    end

    subgraph Chain213[链 213: 1个事件]
        normal_deng_gao[normal_d]
    end

    subgraph Chain214[链 214: 1个事件]
        normal_du_zhuo[normal_d]
    end

    subgraph Chain215[链 215: 1个事件]
        normal_deepseek[normal_d]
    end

    subgraph Chain216[链 216: 1个事件]
        test1[test1]
    end

    subgraph Chain217[链 217: 1个事件]
        martial_sword_dance[martial_]
    end

    subgraph Chain218[链 218: 1个事件]
        elegant_qin_recital[elegant_]
    end

    subgraph Chain219[链 219: 1个事件]
        event_death_health_n[event_de]
    end

    subgraph Chain220[链 220: 1个事件]
        default_ambition[default_]
    end

    subgraph Chain221[链 221: 1个事件]
        dufu_ambition[dufu_amb]
    end

    subgraph Chain222[链 222: 1个事件]
        ambition_loushi[ambition]
    end

    subgraph Chain223[链 223: 1个事件]
        event_money_lower_0[event_mo]
    end

    subgraph Chain224[链 224: 1个事件]
        event_ambition_start[event_am]
    end

    subgraph Chain225[链 225: 1个事件]
        event_money_lower_0_[event_mo]
    end

    subgraph Chain226[链 226: 1个事件]
        end_of_exam[end_of_e]
    end

    subgraph Chain227[链 227: 1个事件]
        baiye_asking_for_act[baiye_as]
    end

    subgraph Chain228[链 228: 1个事件]
        demonstrate_poem_to_[demonstr]
    end

    subgraph Chain229[链 229: 1个事件]
        environment:flower[environm]
    end

    subgraph Chain230[链 230: 1个事件]
        environment:moon[environm]
    end

    subgraph Chain231[链 231: 1个事件]
        object:medicine[object:m]
    end

    subgraph Chain232[链 232: 1个事件]
        entertain:elegant[entertai]
    end

    subgraph Chain233[链 233: 1个事件]
        entertain:sensual[entertai]
    end

    subgraph Chain234[链 234: 1个事件]
        emotion:despair[emotion:]
    end

    subgraph Chain235[链 235: 1个事件]
        relation:patron[relation]
    end

    subgraph Chain236[链 236: 1个事件]
        emotion:tranquility[emotion:]
    end

    subgraph Chain237[链 237: 1个事件]
        relation:friend[relation]
    end

    subgraph Chain238[链 238: 1个事件]
        society:famine[society:]
    end

    subgraph Chain239[链 239: 1个事件]
        place:jadestep[place:ja]
    end

    subgraph Chain240[链 240: 1个事件]
        emotion:ambition[emotion:]
    end

    subgraph Chain241[链 241: 1个事件]
        health:drunk[health:d]
    end

    subgraph Chain242[链 242: 1个事件]
        politics:cloud[politics]
    end

    subgraph Chain243[链 243: 1个事件]
        object:ink[object:i]
    end

    subgraph Chain244[链 244: 1个事件]
        travel:exile[travel:e]
    end

    subgraph Chain245[链 245: 1个事件]
        travel:parting[travel:p]
    end

    subgraph Chain246[链 246: 1个事件]
        court:prosper[court:pr]
    end

    subgraph Chain247[链 247: 1个事件]
        environment:snow[environm]
    end

    subgraph Chain248[链 248: 1个事件]
        entertain:martial[entertai]
    end

    subgraph Chain249[链 249: 1个事件]
        environment:wind[environm]
    end

    subgraph Chain250[链 250: 1个事件]
        myth:giantroc[myth:gia]
    end

    subgraph Chain251[链 251: 1个事件]
        court:corrupt[court:co]
    end

    subgraph Chain252[链 252: 1个事件]
        rteates[rteates]
    end
